name: Convert Markdown into PDF
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check markdown input directory
        run: |
          echo "Listing ./src/md contents:"
          ls -al ./src/md || echo "⚠️ ./src/md directory not found"

      - name: Convert Markdown into PDF
        uses: KoharaKazuya/marp-cli-action@v2
        with:
          config-file: ./.marprc-ci.yml
          generate-html: true
          generate-pdf: true

      - name: Check output directory
        run: |
          echo "Listing ./output contents after Marp run:"
          ls -al ./output || echo "⚠️ ./output directory not found or empty"

      - name: Check workspace (optional)
        run: |
          echo "Listing entire workspace for debugging:"
          ls -alR

      - name: Save outputs
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
